title: Yanxi Zeng # your name (or website title) here
logo: "/images/曾燕熙证件照.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Social Policy & Data Analysis
<br><br>
    University of Pennsylvania
<br><br>
<br><br>
<br><br>
  <a href="https://www.linkedin.com/in/yanxi-zeng-277b83176/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
